src/docs/get-started/install/index.md

翻译完成 index.md
完成 Issue #2 
@inferjay

[翻译完成] flutter.cn/src/docs/get-started/install/index.md

---

src/docs/get-started/install/index.md

[UPDATE]get-started/install/index.md

---

src/_data/sidenav.yml
src/_includes/important.html
src/_includes/tip.html
src/_includes/warning.html
src/_layouts/base.html
src/docs/codelabs/index.md
src/docs/cookbook/animation/opacity-animation.md
src/docs/cookbook/design/drawer.md
src/docs/cookbook/design/fonts.md
src/docs/cookbook/design/orientation.md
src/docs/cookbook/design/package-fonts.md
src/docs/cookbook/design/snackbars.md
src/docs/cookbook/design/tabs.md
src/docs/cookbook/design/themes.md
src/docs/cookbook/forms/focus.md
src/docs/cookbook/forms/retrieve-input.md
src/docs/cookbook/forms/text-field-changes.md
src/docs/cookbook/forms/text-input.md
src/docs/cookbook/forms/validation.md
src/docs/cookbook/index.md
src/docs/deployment/android.md

Common resource translations test

---

src/docs/get-started/codelab.md
src/docs/get-started/editor.md
src/docs/get-started/flutter-for/android-devs.md
src/docs/get-started/flutter-for/ios-devs.md
src/docs/get-started/flutter-for/react-native-devs.md
src/docs/get-started/flutter-for/web-devs.md
src/docs/get-started/flutter-for/xamarin-forms-devs.md
src/docs/get-started/index.md
src/docs/get-started/install/index.md
src/docs/get-started/install/linux.md
src/docs/get-started/install/macos.md
src/docs/get-started/install/windows.md
src/docs/get-started/learn-more.md
src/docs/get-started/test-drive/index.md
src/docs/index.md

titles translation for the get-started section

---

src/docs/get-started/flutter-for/web-devs.md

Translate Flutter for web developers into Chinese, details at issue #19 
Flutter for web developers 一文的翻译工作，详见 Issue #19

Flutter for web developers' translation (CN)

---

src/docs/get-started/flutter-for/web-devs.md

翻译完成 flutter.cn/src/docs/get-started/editor.md
完成 Issue #22
关于 Android Studio 和 IntelliJ 不了解是否有中文支持，对于 IDE 的操作未作翻译。

 [翻译完成] flutter.cn/src/docs/get-started/editor.md 

---

src/docs/cookbook/testing/unit/introduction.md
src/docs/cookbook/testing/unit/mocking.md

 [翻译完成] flutter.cn/src/docs/cookbook/testing/unit/mocking.md

---

src/docs/cookbook/design/tabs.md

…ok/design/tabs.md
翻译完成 tabs.md
完成issue #80
@inferjay

[翻译完成] https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/design/tabs.md

---

src/docs/cookbook/design/package-fonts.md

完成翻译 package-fonts.md
完成 issue #79
@chenglu

[翻译完成] https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/design/package-fonts.md

---

src/docs/cookbook/animation/opacity-animation.md

完成翻译 opacity-animation.md
完成issue #78
@chenglu

[翻译完成] https://debug.flutter.cn/docs/cookbook/animation/opacity-animation.html

---

src/docs/cookbook/animation/opacity-animation.md

突然发现老稿中有个错别词，提出一下修正
URL: https://debug.flutter.cn/docs/cookbook/animation/opacity-animation.html
原译者：@Vadaski
原 PR：#96
原 Issue：#78
感谢原译者的优秀翻译！

Fix typo: cookbook\animation\opacity-animation.md

---

src/docs/cookbook/design/themes.md

Translate themes.md

---

src/docs/cookbook/navigation/navigation-basics.md

翻译完成 navigation-basics.md
完成 Issue #125

[翻译完成] flutter.cn/src/docs/cookbook/navigation/navigation-basics.md

---

src/docs/cookbook/gestures/handling-taps.md

翻译完成 handling-taps.md
完成 Issue #112

[翻译完成] flutter.cn/src/docs/cookbook/gestures/handling-taps.md

---

src/docs/cookbook/lists/basic-list.md

翻译完成 basic-list.md
完成 Issue #117

[翻译完成] flutter.cn/src/docs/cookbook/lists/basic-list.md

---

src/docs/resources/platform-adaptations.md

翻译完成 flutter.cn/src/docs/resources/platform-adaptations.md
完成 Issue #200

[翻译完成] flutter.cn/src/docs/resources/platform-adaptations.md

---

src/docs/cookbook/navigation/passing-data.md

翻译完成 passing-data.md
完成 Issue #129

[翻译完成] flutter.cn/src/docs/cookbook/navigation/passing-data.md

---

src/docs/get-started/codelab.md

codelab.md 编写你的第一个应用 错别字修改

---

src/docs/development/packages-and-plugins/developing-packages.md

翻译完成 flutter.cn/src/docs/development/packages-and-plugins/developing-packages.md
完成 Issue #171

[翻译完成] flutter.cn/src/docs/development/packages-and-plugins/developing-packages.md

---

src/docs/development/ui/advanced/slivers.md

[翻译完成]  flutter.cn/src/docs/development/ui/advanced/slivers.md

---

src/docs/cookbook/navigation/returning-data.md

翻译完成 returning-data.md
完成 Issue #128

[翻译完成] flutter.cn/src/docs/cookbook/navigation/returning-data.md

---

src/docs/cookbook/forms/text-input.md

翻译完成 text-input.md
完成 Issue #107

[翻译完成] flutter.cn/src/docs/cookbook/forms/text-input.md

---

src/docs/cookbook/forms/retrieve-input.md

翻译完成 retrieve-input.md
完成 Issue #110

[翻译完成] flutter.cn/src/docs/cookbook/forms/retrieve-input.md

---

src/docs/cookbook/images/network-image.md

[翻译完成] flutter.cn/src/docs/cookbook/images/network-image.md

---

src/docs/cookbook/lists/grid-lists.md

翻译完成 grid-list.md
完成 Issue #119

[翻译完成] flutter.cn/src/docs/cookbook/lists/grid-lists.md

---

src/docs/cookbook/forms/text-field-changes.md

text-field-changes.md 翻译完成
Issues https://github.com/cfug/flutter.cn/issues/109

[翻译完成]  flutter.cn/src/docs/cookbook/forms/text-field-changes.md

---

src/docs/testing/index.md

翻译完成 flutter.cn/src/docs/testing/index.md
完成 Issue #182

[翻译完成] flutter.cn/src/docs/testing/index.md

---

src/docs/cookbook/lists/horizontal-list.md

翻译完成 horizontal-list.md
完成 Issue #118

[翻译完成] flutter.cn/src/docs/cookbook/lists/horizontal-list.md

---

src/docs/get-started/flutter-for/declarative.md

翻译完成 declarative.md
完成 Issue #217

[翻译完成] src/docs/get-started/flutter-for/declarative.md

---

src/docs/cookbook/forms/validation.md

翻译完成 validation.md
完成 Issue #105

[翻译完成] flutter.cn/src/docs/cookbook/forms/validation.md

---

src/docs/development/ui/layout/box-constraints.md

翻译完成 flutter.cn/src/docs/development/ui/layout/box-constraints.md
完成 Issue #148 
@chenglu

[翻译完成] flutter.cn/src/docs/development/ui/layout/box-constraints.md

---

src/docs/cookbook/lists/long-lists.md

翻译完成 long-lists.md
完成 Issue #122

[翻译完成] flutter.cn/src/docs/cookbook/lists/long-lists.md

---

src/docs/cookbook/navigation/navigate-with-arguments.md

翻译完成 navigate-with-arguments.md
完成 Issue #127

[翻译完成] flutter.cn/src/docs/cookbook/navigation/navigate-with-arguments.md

---

src/docs/cookbook/design/snackbars.md

翻译完成 src/docs/cookbook/design/snackbars.md
完成 Issue #101

[翻译完成] src/docs/cookbook/design/snackbars.md

---

src/docs/cookbook/testing/widget/finders.md
src/docs/cookbook/testing/widget/introduction.md

翻译完成 An introduction to widget testing.md
完成issue #142

[翻译完成]flutter.cn/src/docs/cookbook/testing/widget/introduction.md

---

src/docs/cookbook/navigation/hero-animations.md

翻译完成 hero-animations.md
完成 Issue #124

[翻译完成] flutter.cn/src/docs/cookbook/navigation/hero-animations.md

---

src/docs/cookbook/maintenance/error-reporting.md

翻译完成 error-reporting.md
完成 Issue #123

[翻译完成] flutter.cn/src/docs/cookbook/maintenance/error-reporting.md

---

src/docs/cookbook/plugins/play-video.md

翻译完成 play-video.md
完成 Issue #137

[翻译完成] flutter.cn/src/docs/cookbook/plugins/play-video.md

---

src/docs/cookbook/images/fading-in-images.md

翻译完成 flutter.cn/src/docs/cookbook/images/fading-in-images.md 
完成 Issue #115 
From asset bundle 应该是和 In-Memory 同级吧，原文中一个是三级标题一个是二级标题

[翻译完成] flutter.cn/src/docs/cookbook/images/fading-in-images.md 

---

src/docs/cookbook/images/cached-images.md

翻译完成 flutter.cn/src/docs/cookbook/images/cached-images.md
完成 Issue #116

[翻译完成] flutter.cn/src/docs/cookbook/images/cached-images.md

---

src/docs/cookbook/lists/mixed-list.md

翻译完成 mixed-lists.md
完成 Issue #120

 [翻译完成] flutter.cn/src/docs/cookbook/lists/mixed-lists.md

---

src/docs/cookbook/testing/widget/finders.md
src/docs/cookbook/testing/widget/introduction.md
src/docs/development/ui/animations/index.md

[翻译完成] flutter.cn/src/docs/development/ui/animations/index.md

---

src/docs/testing/oem-debuggers.md

翻译完成 flutter.cn/src/docs/testing/oem-debuggers.md
完成 Issue #180

[翻译完成] flutter.cn/src/docs/testing/oem-debuggers.md

---

src/docs/cookbook/persistence/key-value.md

翻译完成 key-value.md
完成 Issue #136

[翻译完成] src/docs/cookbook/persistence/key-value.md

---

src/docs/development/tools/formatting.md

翻译完成 flutter.cn/src/docs/development/tools/formatting.md
完成 Issue #178

[翻译完成] flutter.cn/src/docs/development/tools/formatting.md

---

src/docs/cookbook/networking/authenticated-requests.md

翻译完成 authenticated-requests.md
完成 Issue [#48](https://github.com/cfug/flutter.cn/issues/131)

[翻译完成] flutter.cn/src/docs/cookbook/networking/authenticated-requests.md

---

src/docs/development/ui/navigation.md

翻译完成 src/docs/development/ui/navigation.md
完成 #151

[翻译完成] src/docs/development/ui/navigation.md

---

src/docs/development/ui/widgets/index.md

翻译完成 src/docs/development/ui/widgets/index.md
完成 #159

翻译完成 src/docs/development/ui/widgets/index.md

---

src/docs/development/data-and-backend/state-mgmt/intro.md

翻译完成 src/docs/development/data-and-backend/state-mgmt/intro.md
完成 #160

翻译完成 src/docs/development/data-and-backend/state-mgmt/intro.md

---

src/docs/development/data-and-backend/firebase.md

翻译完成  src/docs/development/data-and-backend/firebase.md
完成 #166

翻译完成  src/docs/development/data-and-backend/firebase.md

---

src/docs/development/packages-and-plugins/background-processes.md

翻译完成 src/docs/development/packages-and-plugins/background-processes.md
完成 issue #172

翻译完成 src/docs/development/packages-and-plugins/background-processes.md

---

src/docs/reference/widgets.md

翻译完成 src/docs/reference/widgets.md
完成 Issue #193

翻译完成 src/docs/reference/widgets.md

---

src/docs/resources/bootstrap-into-dart.md

翻译完成 bootstrap-into-dart.md
完成 Issue #189

[翻译完成] src/docs/resources/bootstrap-into-dart.md

---

src/docs/get-started/flutter-for/android-devs.md

翻译完成 android-devs.md
完成 Issue #97

[翻译完成] flutter.cn/src/docs/get-started/flutter-for/android-devs.md

---

src/docs/cookbook/plugins/picture-using-camera.md

翻译完成 picture-using-camera.md
完成 Issue #138

[翻译完成] flutter.cn/src/docs/cookbook/plugins/picture-using-camera.md

---

src/docs/cookbook/networking/web-sockets.md

翻译完成 web-sockets.md
完成 Issue [#50](https://github.com/cfug/flutter.cn/issues/133)

[翻译完成] flutter.cn/src/docs/cookbook/networking/web-sockets.md

---

src/docs/cookbook/gestures/dismissible.md

翻译完成 dismissible.md
完成 Issue #113

[翻译完成] flutter.cn\src\docs\cookbook\gestures\dismissible.md

---

src/docs/cookbook/navigation/named-routes.md

翻译完成 named-routes.md
完成 Issue #126

[翻译完成] flutter.cn/src/docs/cookbook/navigation/named-routes.md

---

src/docs/cookbook/gestures/ripples.md

[翻译完成] flutter.cn/src/docs/cookbook/gestures/ripples.md

---

src/docs/development/tools/vs-code.md

[翻译完成] flutter.cn/src/docs/development/tools/vs-code.md

---

src/docs/cookbook/networking/fetch-data.md

翻译完成 fetch-data.md
完成 Issue [#47](https://github.com/cfug/flutter.cn/issues/130)

[翻译完成] flutter.cn/src/docs/cookbook/networking/fetch-data.md

---

src/docs/cookbook/networking/background-parsing.md

翻译完成 background-parsing.md
完成 Issue [#49](https://github.com/cfug/flutter.cn/issues/132)

[翻译完成] flutter.cn/src/docs/cookbook/networking/background-parsing.md

---

src/docs/cookbook/testing/integration/introduction.md

翻译完成 introduction.md
完成 Issue #139

[翻译完成] flutter.cn/src/docs/cookbook/testing/integration/introduction.md

---

src/docs/cookbook/testing/widget/tap-drag.md

翻译完成 tap-drag.md
完成 Issue #144

[翻译完成] flutter.cn/src/docs/cookbook/testing/widget/tap-drag.md

---

src/docs/development/ui/advanced/gestures.md

[翻译完成] flutter.cn/src/docs/development/ui/advanced/gestures.md

---

src/docs/resources/inside-flutter.md

翻译完成 flutter.cn/src/docs/resources/inside-flutter.md
完成 Issue #190

[翻译完成] flutter.cn/src/docs/resources/inside-flutter.md

---

src/docs/testing/ui-performance/index.md

[翻译完成] flutter.cn/src/docs/cookbook/testing/ui-performance/index.md

---

src/docs/development/data-and-backend/state-mgmt/options.md

翻译完成 flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/options.md
完成 Issue #164 （#83 - Options - 状态管理参考）

[翻译完成] flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/options.md

---

src/docs/development/ui/assets-and-images.md

【翻译完成】flutter.cn/src/docs/development/ui/assets-and-images.md

---

src/docs/development/data-and-backend/state-mgmt/simple.md

[翻译完成]flutter.cn⁩/src/⁨docs/⁨development/⁨data-and-backend⁩/state-mgmt⁩/simple.md

---

src/docs/deployment/ios.md

[翻译完成] src/docs/depolyment/ios.md

---

src/docs/development/tools/sdk/upgrading.md

[翻译完成] src/docs/development/tools/sdk/upgrading.md

---

src/docs/development/ui/animations/tutorial.md

【翻译完成】flutter.cn/tree/master/src/docs/development/ui/animations/tutorial.md

---

src/docs/resources/videos.md

[翻译完成] src/docs/resources/videos.md

---

src/docs/development/platform-integration/platform-channels.md

[翻译完成] flutter.cn/src/docs/development/platform-integration/platform-channels.md

---

src/docs/development/packages-and-plugins/developing-packages.md

[更新]flutter.cn/src/docs/development/packages-and-plugins/developing-packages.md

---

src/docs/development/ui/layout/tutorial.md

src/docs/development/ui/layout/tutorial.md initially completed. 
related issue : https://github.com/cfug/flutter.cn/issues/147.

src/docs/development/ui/layout/tutorial.md initially completed.

---

src/docs/development/ui/widgets-intro.md

[翻译完成] flutter.cn/src/docs/development/ui/widgets-intro.md

---

src/docs/development/data-and-backend/firebase.md

fix: <<<<<<< HEAD

---

src/docs/development/ui/layout/index.md

Fixed the translation issue of 'Flutter 中的布局'

---

src/docs/cookbook/testing/widget/introduction.md

[sync] 2019/6/28

---

src/docs/codelabs/layout-basics.md
src/docs/deployment/android.md
src/docs/development/data-and-backend/json.md

[sync] 2019/7/1

---

src/docs/get-started/install/_get-sdk-win.md

fixed Issue #380

---

examples/internationalization/intl_example/lib/main.dart
src/_data/sidenav.yml
src/docs/get-started/flutter-for/android-devs.md

[sync] 2019/7/3

---

src/docs/cookbook/plugins/play-video.md
src/docs/development/accessibility-and-localization/internationalization.md

[sync] 2019/7/6

---

src/_data/sidenav.yml
src/docs/cookbook/animation/page-route-animation.md
src/docs/development/packages-and-plugins/androidx-compatibility.md
src/docs/development/tools/devtools/android-studio.md
src/docs/development/tools/devtools/cli.md
src/docs/development/tools/devtools/debugger.md
src/docs/development/tools/devtools/index.md
src/docs/development/tools/devtools/inspector.md
src/docs/development/tools/devtools/logging.md
src/docs/development/tools/devtools/memory.md
src/docs/development/tools/devtools/overview.md
src/docs/development/tools/devtools/timeline.md
src/docs/development/tools/devtools/vscode.md
src/docs/development/tools/sdk/releases.md
src/docs/get-started/flutter-for/react-native-devs.md
src/docs/index.md
src/docs/resources/faq.md
src/docs/testing/code-debugging.md

[sync] 2019/7/11

---

src/brand.md
src/docs/resources/faq.md

[sync] 2019/7/16

---

examples/animation/animate2/lib/main.dart
examples/animation/animate3/lib/main.dart
examples/animation/animate5/lib/main.dart
src/docs/development/platform-integration/platform-channels.md
src/docs/index.md
src/web.md

[sync] 2019/7/19

---

src/docs/testing/ui-performance.md

更新了 ui-performance.md 的内容
完成 issue #416

【更新完成】Update ui-performance.md

---

src/_includes/banner.html
src/docs/cookbook/animation/animated-container.md
src/docs/development/data-and-backend/json.md
src/docs/development/tools/sdk/upgrading.md
src/docs/development/ui/assets-and-images.md
src/docs/get-started/install/_get-sdk-win.md

[sync] 2019/8/13

---

_config.yml
src/docs/codelabs/dart-cheatsheet.md

Fixed the issue #431

---

AUTHORS
src/docs/development/data-and-backend/firebase.md
src/docs/development/platform-integration/platform-channels.md

[sync] 2019/8/28

---

src/docs/testing/debugging.md

翻译完成 debugging.md
完成 Issue #397

[翻译完成] flutter.cn/src/docs/testing/debugging.md

---

src/posts/flutter-news-from-gdd-china-flutter1.9.md

1.9 news post

---

src/_includes/banner.html

@Vadaski 
The blank issue will be fixed w/ this PR, FYI.

Removed the extra elements on banner.html

---

src/docs/get-started/flutter-for/declarative.md

[sync] 2019/10/1

---

.travis.yml
firebase.json
src/docs/cookbook/gestures/ripples.md
tool/check-code.sh

[sync] 2019/10/10

---

example/pubspec.lock
examples/animation/animate2/lib/main.dart
examples/animation/animate3/lib/main.dart
examples/animation/animate5/lib/main.dart
pubspec.lock
src/docs/codelabs/layout-basics.md
src/docs/cookbook/persistence/sqlite.md
src/docs/deployment/android.md
src/docs/deployment/cd.md
src/docs/development/packages-and-plugins/developing-packages.md
src/docs/development/ui/animations/tutorial.md
src/docs/get-started/install/_ios-setup.md

[sync] 2019/10/16

---

src/docs/get-started/flutter-for/react-native-devs.md

it contains immutable data (它包含不可数的数据 =>它包含不可变的数据)

---

src/docs/development/platform-integration/web.md

替换 google.com 为 google.cn
统一标题大小为三号标题
ref: #499

fix web.md

---

src/docs/development/ui/widgets-intro.md

[修复译误] https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/widgets-intro.md

---

src/docs/development/tools/devtools/performance.md

finish performance.md,  thanks for @chenglu @Vadaski 's help.
Will keep tracing if issues.
ref #415

performance.md translation is done

---

src/docs/cookbook/testing/widget/tap-drag.md
src/docs/release/breaking-changes/template.md

[sync] 2019/11/16

---

.gitignore
firebase.json
src/_data/sidenav.yml
src/_includes/banner.html
src/docs/catalog/samples/expansion-tile-sample.md
src/docs/codelabs/implicit-animations.md
src/docs/development/data-and-backend/json.md
src/docs/development/ui/animations/implicit-animations.md
src/docs/development/ui/animations/index.md

ref #374 
- /_includes/banner.html banner 去掉调查表，新增 implicit-animations，由于未翻译，暂时不放 banner
- codelabs/implicit-animations.md 新增脚注
- /development/data-and-backend/json.md 新增 site alert，以及通过 isolate 解析 JSON 的 cookbook
- 新增 implicit-animations.md 隐式动画，需要翻译。
- development/ui/animations/index.md 新增隐式动画的链接

[sync] 2019/12/4

---

src/_includes/banner.html
src/docs/codelabs/implicit-animations.md
src/docs/get-started/web.md
src/docs/index.md

[sync] 2019/12/12

---

src/docs/development/add-to-app/ios/project-setup.md

[翻译完成] Integrate a Flutter module into your iOS project

---

src/docs/development/add-to-app/android/add-splash-screen.md

[sync] 2019/12/26

---

src/_data/sidenav.yml

- 翻译了遗漏的英文标题
- 更新了 google fonts 的链接指向
ref: #570

fixed sidenav issues

---

src/_data/sidenav.yml

fixed sidenav issue

---

src/docs/development/add-to-app/ios/add-flutter-screen.md

[翻译完成] src/docs/development/add-to-app/ios/add-flutter-screen.md

---

src/docs/development/androidx-migration.md

[翻译完成] src/docs/development/androidx-migration.md

---

src/docs/cookbook/forms/text-field-changes.md

- 修复一处译误
感谢 @nanjolnoSat 的反馈 ref: #594

fixed mistranslation

---

src/docs/development/add-to-app/android/add-splash-screen.md

[翻译完成] src/docs/development/add-to-app/android/add-splash-screen

---

src/_data/sidenav.yml
src/docs/codelabs/layout-basics.md
src/docs/cookbook/forms/validation.md
src/docs/cookbook/lists/mixed-list.md
src/docs/cookbook/navigation/hero-animations.md
src/docs/cookbook/navigation/named-routes.md
src/docs/cookbook/testing/integration/profiling.md
src/docs/deployment/cd.md
src/docs/deployment/web.md
src/docs/development/add-to-app/debugging.md
src/docs/development/data-and-backend/firebase.md
src/docs/development/tools/sdk/_os.md
src/docs/development/tools/sdk/releases.md
src/docs/perf/rendering/best-practices.md
src/docs/resources/bootstrap-into-dart.md
src/docs/resources/faq.md
src/docs/resources/platform-adaptations.md
src/docs/testing/errors.md

Fixed all the typo issues:
#566 #589 #565 #568 #555 #556 #558 #564 #551 #552 #553 #554 #559 #560 #561 #563

Typo fixing.

---

src/_layouts/base.html

Add Baidu Search Engine pings here.

Add Baidu Ping.

---

src/docs/get-started/flutter-for/ios-devs.md

awati -> await

---

src/_layouts/base.html
src/community/china.md

site updates

---

README.md
src/_assets/js/main.js
src/_data/sidenav.yml
src/_includes/banner.html
src/docs/cookbook/lists/mixed-list.md
src/docs/cookbook/testing/integration/introduction.md
src/docs/cookbook/testing/unit/introduction.md
src/docs/cookbook/testing/widget/introduction.md
src/docs/development/accessibility-and-localization/internationalization.md
src/docs/development/add-to-app/android/plugin-setup.md
src/docs/development/add-to-app/ios/add-flutter-screen.md
src/docs/development/add-to-app/ios/project-setup.md
src/docs/development/ui/widgets-intro.md
src/docs/get-started/flutter-for/web-devs.md
src/docs/release/breaking-changes/add-showAutocorrectionPromptRect.md
src/docs/release/breaking-changes/index.md
src/docs/release/breaking-changes/rendereditable-layout-before-hit-test.md
src/docs/testing/index.md
src/docs/testing/oem-debuggers.md

- _data/sidenav.yml 新增 Android Plugin 初始化nav
- _includes/banner.html codepen 现已支持 Flutter！
- cookbook/testing/widget/introduction.md widget test 更新了关于 pump 的描述
- development/add-to-app/android/plugin-setup.md add to app 新增 初始化 plugin 需要翻译
- release/breaking-changes/add-showAutocorrectionPromptRect.md `TextInputClient` 新增 breaking changes`showAutocorrectionPromptRect` 方法
- release/breaking-changes/rendereditable-layout-before-hit-test.md 新增 breaking changes 在进行点击测试之前，需要对 RenderEditable 进行布局 需要翻译

[sync] 2020/4/16

---

src/docs/resources/compatibility.md

翻译完成 compatibility.md
完成 Issue #583

[翻译完成] src/docs/resources/compatibility.md

---

src/docs/testing/errors.md

翻译完成 errors.md
完成 Issue [#585](https://github.com/cfug/flutter.cn/issues/585)
@Vadaski

[翻译完成] flutter.cn/src/docs/testing/errors.md

---

src/posts/announcing-adobe-xd-support-for-flutter.md

add official post

---

src/docs/codelabs/explicit-animations.md
src/docs/development/platform-integration/platform-channels.md
src/docs/get-started/codelab-web.md
src/docs/get-started/install/_path-mac.md

[sync] 2020/5/18

---

src/docs/cookbook/testing/integration/introduction.md

typo fixed (#649)

---

src/_includes/banner.html
src/desktop.md
src/docs/cookbook/images/network-image.md
src/docs/cookbook/persistence/sqlite.md
src/docs/deployment/flavors.md
src/docs/deployment/web.md
src/docs/get-started/install/_get-sdk.md
src/docs/get-started/web.md
src/index.html

[sync] 2020/5/22

---

src/docs/development/tools/devtools/inspector.md
src/docs/testing/debugging.md

[sync] 2020/05/31

---

firebase.json
src/docs/cookbook/networking/send-data.md
src/docs/cookbook/testing/unit/mocking.md
src/docs/development/add-to-app/android/add-flutter-fragment.md
src/docs/development/platform-integration/platform-channels.md
src/docs/development/tools/vs-code.md
src/docs/development/ui/layout/index.md
src/docs/get-started/install/_android-setup.md
src/docs/get-started/install/linux.md
src/docs/resources/technical-overview.md

ref #374 for docs sync.
also fixes #657

[sync] 2020/6/3

---

firebase.json
src/_includes/dart-tool.md
src/docs/cookbook/testing/integration/profiling.md
src/docs/deployment/flavors.md
src/docs/development/ui/animations/hero-animations.md
src/docs/development/ui/animations/tutorial.md
src/docs/get-started/codelab-web.md
src/docs/release/breaking-changes/dialog-border-radius.md
src/docs/release/breaking-changes/index.md

[sync] 2020/6/12

---

src/community/tutorials/index.md
src/community/tutorials/memory-leak-monitoring-on-flutter.md

2nd community tutorial about the memory leak monitoring on flutter by the Kwai team.

community tutorial: add & landing

---

src/docs/development/ui/layout/constraints.md

翻译完成：constraints.md
完成 issue :  https://github.com/cfug/flutter.cn/issues/667
cc/ @chenglu

[完成翻译] /docs/development/ui/layout/constraints.md

---

src/docs/development/ui/layout/constraints.md

[fix] typo

---

src/_assets/css/_banner.scss
src/docs/catalog/samples/index.md
src/docs/cookbook/testing/unit/introduction.md
src/docs/development/androidx-migration.md
src/docs/development/tools/devtools/vscode.md
src/docs/development/tools/vs-code.md
src/docs/get-started/codelab.md
src/docs/get-started/editor.md
src/docs/get-started/test-drive/_vscode.md
src/docs/index.md
src/docs/testing/index.md

ref #374 
更新内容：
- 主要是 VS Code 里的调试功能的 UI 改动，从 Debug 按钮变成了 Run 按钮

[sync] 2020/7/4

---

firebase.json
src/desktop.md
src/docs/development/add-to-app/ios/project-setup.md
src/docs/development/data-and-backend/state-mgmt/declarative.md
src/docs/development/data-and-backend/state-mgmt/ephemeral-vs-app.md
src/docs/development/data-and-backend/state-mgmt/options.md
src/docs/development/data-and-backend/state-mgmt/simple.md
src/docs/development/ui/assets-and-images.md
src/docs/get-started/install/_get-sdk-linux.md
src/docs/get-started/install/linux.md

ref #374 
增加 Flutter Linux 的安装说明（需要翻译）
- src/docs/get-started/install/_get-sdk-linux.md
状态管理页面大更新（需要翻译）
- src/docs/development/data-and-backend/state-mgmt/options.md
另外，Flutter Desktop 的文档也加速一下翻译进度吧
- src/desktop.md

[sync] 2020/7/19

---

src/docs/development/packages-and-plugins/plugin-api-migration.md

Finish and closing issue: 
fixes #578

[翻译完成] docs/development/packages-and-plugins/plugin-api-migration.md

---

src/docs/development/data-and-backend/state-mgmt/options.md

Resolves #691 .
由于有些内容不是特别熟悉，在措辞上还需要看看有没有问题。 😆

[翻译完成] /docs/development/data-and-backend/state-mgmt/options.md

---

src/docs/development/add-to-app/android/project-setup.md

翻译完成：project-setup.md
完成 issue : #535 
@Vadaski

[完成翻译] /docs/development/add-to-app/android/project-setup.md

---

_config.yml
firebase.json
src/_data/catalog/widgets.json
src/_data/sidenav.yml
src/desktop.md
src/docs/cookbook/lists/mixed-list.md
src/docs/development/accessibility-and-localization/accessibility.md
src/docs/development/data-and-backend/json.md
src/docs/development/packages-and-plugins/developing-packages.md
src/docs/development/ui/layout/constraints.md
src/docs/get-started/install/index.md
src/docs/release/breaking-changes/hero-controller-scope.md
src/docs/release/breaking-changes/index.md
src/docs/testing/code-debugging.md

ref #374 
主要更新：
- 安装页面的 UI 小更新

[sync] 2020/7/23

---

src/docs/development/packages-and-plugins/plugin-api-migration.md

typo fixes on plugin-api-migration.md

---

src/search-all.html
src/search.html

ref: https://github.com/cfug/team/issues/13

flutter search:on project init

---

src/docs/development/add-to-app/android/project-setup.md

This is a quick fix to resolve #700 . Add a line wrap to the specific alert section.

Fix alert content format for #700

---

firebase.json
src/_data/showcases.yml
src/_data/sidenav.yml
src/docs/catalog/samples/basic-app-bar.md
src/docs/development/add-to-app/android/project-setup.md
src/docs/development/tools/vs-code.md
src/docs/get-started/install/_android-setup-chromeos.md
src/docs/get-started/install/_get-sdk-chromeos.md
src/docs/get-started/install/chromeos.md
src/docs/perf/rendering/best-practices.md
src/docs/perf/rendering/ui-performance.md
src/f/flutter-survey-metadata.json

ref #374 
VS Code 在调试过程中的快捷键更新：
- 热重载快捷键：从 `Ctrl`/`Cmd`+`Shift`+`F5` 更新为 `Ctrl`/`Cmd`+`F5`

[sync] 2020/7/29

---

examples/internationalization/add_language/lib/main.dart
firebase.json
src/docs/codelabs/index.md
src/docs/cookbook/testing/unit/introduction.md
src/docs/development/add-to-app/android/project-setup.md
src/docs/development/add-to-app/ios/project-setup.md
src/docs/development/packages-and-plugins/using-packages.md
src/docs/development/platform-integration/web.md
src/docs/development/tools/sdk/release-notes/index.md
src/docs/get-started/test-drive/index.md
src/docs/perf/rendering/shader.md
src/docs/perf/rendering/ui-performance.md
src/docs/testing/index.md
src/docs/whats-new-archive.md

[sync] 2020/08/09

---

_config.yml
firebase.json
src/docs/cookbook/design/fonts.md
src/docs/development/add-to-app/android/project-setup.md
src/docs/development/data-and-backend/firebase.md
src/docs/development/data-and-backend/state-mgmt/options.md
src/docs/development/tools/devtools/inspector.md
src/docs/development/ui/assets-and-images.md
src/docs/get-started/flutter-for/react-native-devs.md
src/docs/get-started/install/_get-sdk-win.md
src/docs/perf/rendering/ui-performance.md
src/docs/resources/architectural-overview.md
src/docs/resources/faq.md
src/docs/testing/debugging.md
src/docs/whats-new-archive.md

[sync] 2020/08/20

---

firebase.json
src/_includes/banner.html
src/docs/development/add-to-app/debugging.md
src/docs/development/packages-and-plugins/developing-packages.md
src/docs/development/platform-integration/c-interop.md
src/docs/get-started/flutter-for/web-devs.md
src/docs/get-started/install/_android-setup.md
src/docs/index.md
src/docs/release/breaking-changes/actions-api-revision.md
src/docs/release/breaking-changes/add-currentAutofillScope-to-TextInputClient.md
src/docs/release/breaking-changes/add-showAutocorrectionPromptRect.md
src/docs/release/breaking-changes/android-v1-embedding-create-deprecation.md
src/docs/release/breaking-changes/container-color.md
src/docs/release/breaking-changes/cupertino-tab-bar-localizations.md
src/docs/release/breaking-changes/dialog-border-radius.md
src/docs/release/breaking-changes/form-field-autovalidation-api.md
src/docs/release/breaking-changes/hero-controller-scope.md
src/docs/release/breaking-changes/index.md
src/docs/release/breaking-changes/material-chip-button-semantics.md
src/docs/release/breaking-changes/modal-router-semantics-order.md
src/docs/release/breaking-changes/network-policy-ios-android.md
src/docs/release/breaking-changes/rendereditable-layout-before-hit-test.md
src/docs/release/breaking-changes/route-transition-record-and-transition-delegate.md
src/docs/release/breaking-changes/services-scheduler-dependency-reversed.md
src/docs/release/breaking-changes/test-widgets-flutter-binding-clock.md
src/docs/release/breaking-changes/text-field-material-localizations.md
src/docs/testing/errors.md

[sync] 2020/8/31

---

src/docs/deployment/ios.md

typo fixes

---

src/_includes/banner.html

[update] banner

---

src/_includes/banner.html
src/docs/deployment/ios.md
src/docs/get-started/install/_android-setup-chromeos.md
src/docs/get-started/install/_get-sdk-chromeos.md
src/docs/get-started/install/_get-sdk-linux.md
src/docs/get-started/install/_path-linux-chromeos.md

[完成翻译]  get-started install 相关内容

---

firebase.json
src/_data/showcases.yml
src/_data/sidenav.yml
src/community/china.md
src/docs/cookbook/networking/authenticated-requests.md
src/docs/cookbook/networking/background-parsing.md
src/docs/cookbook/networking/delete-data.md
src/docs/cookbook/networking/fetch-data.md
src/docs/cookbook/networking/send-data.md
src/docs/cookbook/networking/update-data.md
src/docs/cookbook/testing/integration/introduction.md
src/docs/cookbook/testing/unit/mocking.md
src/docs/deployment/ios.md
src/docs/development/platform-integration/ios-app-clip.md
src/docs/development/tools/sdk/upgrading.md
src/docs/development/ui/advanced/slivers.md
src/docs/get-started/codelab.md
src/docs/get-started/flutter-for/android-devs.md
src/docs/get-started/flutter-for/ios-devs.md
src/docs/get-started/flutter-for/xamarin-forms-devs.md
src/docs/get-started/install/_get-sdk-chromeos.md
src/docs/get-started/install/_get-sdk-linux.md
src/docs/get-started/install/_get-sdk-win.md
src/docs/get-started/install/_get-sdk.md
src/docs/get-started/install/macos.md
src/docs/perf/rendering/shader.md
src/docs/release/breaking-changes/clip-behavior.md
src/docs/release/breaking-changes/index.md
src/docs/whats-new.md
src/posts/announcing-adobe-xd-support-for-flutter.md

ref #374 
- src/docs/cookbook/testing/integration/introduction.md 新增了一部分内容没有翻译
- src/docs/development/ui/advanced/slivers.md 需要重新安排翻译

[sync] 2020/10/9

---

src/docs/development/tools/devtools/app-size.md

[完成翻译] Using the app size tool.

---

src/docs/get-started/install/_get-sdk.md

Fix: Get SDK document error.

---

src/_data/sidenav.yml
src/docs/development/platform-integration/c-interop.md

[完成翻译] dart:ffi.

---

src/docs/development/platform-integration/platform-views.md

[完成翻译] Platform views

---

src/docs/codelabs/implicit-animations.md

[完成翻译] implicit-animations 

---

src/docs/development/platform-integration/apple-watch.md

[完成翻译] apple watch.

---

src/docs/development/platform-integration/ios-app-clip.md

[完成翻译] ios app clip

---

src/docs/development/data-and-backend/json.md

[内容更新] src/docs/development/data-and-backend/json.md

---

src/docs/development/ui/advanced/splash-screen.md

[内容更新] src/doc/development/ui/advanced/splash-screen.md

---

src/desktop.md

[完成翻译] src/desktop.md

---

src/community/tutorials/understanding-navigator-v2.md
src/docs/development/ui/interactive.md

NOTE: We love contributions, but we hate spam. If your PR doesn't improve flutter.dev, we'll close it and label it as `invalid`.
Changes proposed in this pull request:
*  新增 navigator2.0 教程

navigator2.0 community tutorial

---

examples/internationalization/gen_l10n_example/README.md
examples/internationalization/gen_l10n_example/l10n.yaml
examples/internationalization/gen_l10n_example/lib/l10n/app_en.arb
examples/internationalization/gen_l10n_example/lib/l10n/app_es.arb
examples/internationalization/gen_l10n_example/lib/main.dart
examples/internationalization/gen_l10n_example/pubspec.yaml
firebase.json
src/_data/showcases.yml
src/adoptawidget/index.md
src/desktop.md
src/docs/cookbook/design/fonts.md
src/docs/cookbook/lists/long-lists.md
src/docs/cookbook/persistence/sqlite.md
src/docs/cookbook/plugins/picture-using-camera.md
src/docs/development/accessibility-and-localization/internationalization.md
src/docs/development/data-and-backend/state-mgmt/options.md
src/docs/get-started/flutter-for/android-devs.md
src/docs/get-started/flutter-for/ios-devs.md
src/docs/get-started/flutter-for/react-native-devs.md
src/docs/null-safety.md
src/docs/perf/rendering/shader.md
src/docs/release/breaking-changes/android-setIsRunningInRobolectricTest-removed.md
src/docs/release/breaking-changes/index.md
src/docs/testing/errors.md

[sync] 2020/11/20

---

src/community/tutorials/understanding-navigator-v2.md
src/docs/development/ui/interactive.md

update navigator2.0 community tutorial

---

src/community/tutorials/understanding-navigator-v2.md
src/docs/development/ui/interactive.md

fix translation toggle tools issue and typo fixes

---

src/_includes/banner.html

Add the 2020Q4 survey.

---

src/docs/development/add-to-app/android/_initial-route-cached-engine.md
src/docs/development/add-to-app/android/add-flutter-screen.md

[完成翻译] src/docs/development/add-to-app/android/add-flutter-screen.md

---

src/docs/development/ui/layout/index.md

fix typo in https://flutter.cn/docs/development/ui/layout#lay-out-a-widget

[内容更新] src/docs/development/ui/layout/index.md

---

src/docs/release/breaking-changes/parent-data-widget-generic-type.md

完成翻译 flutter.cn/src/docs/release/breaking-changes/parent-data-widget-generic-type.md
fixes #601

[翻译完成] src/docs/release/breaking-changes/parent-data-widget-generic-type.md

---

src/docs/get-started/flutter-for/android-devs.md

Remove duplicate translation.

---

src/docs/development/add-to-app/android/add-flutter-fragment.md

完成翻译 src/docs/development/add-to-app/android/add-flutter-fragment.md
fixes #576

[完成翻译] src/docs/development/add-to-app/android/add-flutter-fragment.md

---

src/docs/cookbook/navigation/navigate-with-arguments.md
src/docs/development/ui/assets-and-images.md
src/docs/resources/platform-adaptations.md

NOTE: We love contributions, but we hate spam. If your PR doesn't improve flutter.dev, we'll close it and label it as `invalid`.
Fixes #<issue number>.
Changes proposed in this pull request:
*  修复一些拼写错误

[fix] typo fixes

---

src/docs/get-started/install/_get-sdk-win.md

[内容更新] src/docs/get-started/install/windows.md

---

CONTRIBUTING.md
firebase.json
src/docs/codelabs/index.md
src/docs/deployment/web.md
src/docs/development/accessibility-and-localization/internationalization.md
src/docs/development/add-to-app/ios/project-setup.md
src/docs/development/platform-integration/web-images.md
src/docs/get-started/flutter-for/ios-devs.md
src/docs/get-started/install/_get-sdk-linux.md
src/docs/get-started/install/macos.md

[sync] 2020/12/23

---

src/community/china.md

Update SJTUG's description

---

src/_includes/head.html
src/_layouts/base.html

related work:
https://github.com/cfug/team/issues/14

Install GA Code & Remove baidu

---

src/docs/deployment/web.md

[内容更新] src/docs/deployment/web.md

---

src/docs/development/ui/animations/staggered-animations.md

[内容更新] src/docs/development/ui/animations/staggered-animations.md

---

src/docs/perf/rendering/best-practices.md

Improve the content in the document.

[内容更新] src/docs/perf/rendering/best-practices.md

---

src/docs/perf/rendering/ui-performance.md

[内容更新] src/docs/perf/rendering/ui-performance.md

---

src/_includes/head.html
src/_layouts/base.html
src/about/docs-cn.md
src/community/china.md
src/docs/deployment/web.md
src/docs/development/accessibility-and-localization/internationalization.md
src/docs/development/ui/animations/staggered-animations.md
src/docs/perf/rendering/best-practices.md
src/docs/perf/rendering/ui-performance.md
src/docs/testing/code-debugging.md

[完成翻译] src/docs/testing/code-debugging.md

---

src/docs/perf/rendering/ui-performance.md

fix docs/perf/rendering/ui-performance.md.

[fix] Improve doc format

---

src/docs/development/platform-integration/platform-channels.md

[内容更新] src/docs/development/platform-integration/platform-channels.md

---

src/docs/development/add-to-app/index.md

[内容更新] src/docs/development/add-to-app/index.md

---

src/_data/sidenav.yml

sync data src/_data/sidenav.yml.

fix: document sidenav data

---

src/_assets/css/_content.scss
src/docs/perf/rendering/ui-performance.md
src/docs/testing/code-debugging.md

fixes: https://github.com/cfug/team/issues/23

fix: translation format improved for html tag

---

tool/translator/build.sh

such as:
https://debug.flutter.cn/web
https://debug.flutter.cn/desktop
...

[fix] the translation tool not cover the root directory

---

src/docs/get-started/codelab.md

[内容更新] src/docs/get-started/codelab.md

---

src/docs/development/add-to-app/multiple-flutters.md

Fixes #820 .
Also filed a typo correction in https://github.com/flutter/website/pull/5301 .

[翻译完成] src/docs/development/add-to-app/multiple-flutters.md

---

src/docs/development/ui/layout/responsive.md

Fix a typo, 剧左=>居左
NOTE: We love contributions, but we hate spam. If your PR doesn't improve flutter.dev, we'll close it and label it as `invalid`.
Fixes #<issue number>.
Changes proposed in this pull request:
*  
*

Update responsive.md - 一处小笔误，剧左=>居左

---

.github/workflows/build.yml
src/community/tutorials/understanding-navigator-v2.md
src/posts/Flutter-io19.md
tool/before-install.sh
tool/check-code.sh
tool/translator/deploy-cn.sh

本 PR 通过 GitHub Actions 来构建 flutter.cn，已经在自己的 repo 里测试好了，也顺带改了几个文件。
有个问题是，Stable channel 的 code check 我设定为允许错误了，回头还是要改回来的。
Dart.cn 的我今天白天来迁移。

[Migration] From travis-ci to GitHub Actions

---

src/docs/perf/index.md

[翻译完成] src/docs/perf/index.md

---

src/docs/development/ui/navigation/url-strategies.md

[翻译完成]src/docs/development/ui/navigation/url-strategies.md
fixes #834

[翻译完成] src/docs/development/ui/navigation/url-strategies.md

---

src/docs/development/tools/devtools/inspector.md
src/docs/development/ui/advanced/gestures.md
src/docs/development/ui/navigation/url-strategies.md
src/posts/flutter-engage-china-developers-qa-part-1.md

 [翻译完成] src/docs/development/devtools/inspector.md

---

src/docs/perf/app-size.md

[翻译完成]src/docs/perf/app-size.md
fix #581

[翻译完成] src/docs/perf/app-size.md

---

src/docs/development/add-to-app/debugging.md

[翻译完成]  src/docs/development/add-to-app/debugging.md

---

src/docs/perf/app-size.md

#858 根据 @CaiJingLong 大佬的 review 意见，进一步调整了部分文字的措辞。

[内容更新] src/docs/perf/app-size.md

---

src/posts/seamless-multi-platform-app-development-with-flutter.md

add post file seamless-multi-platform-app-development-with-flutter.md

added post

---

src/posts/announcing-dart-2-5-super-charged-development.md
src/posts/announcing-dart-2-6.md
src/posts/announcing-dart-2-8.md
src/posts/announcing-flutter-1-17.md
src/posts/announcing-flutter-1-22.md
src/posts/dart-2-7.md
src/posts/web-support-for-flutter-goes-beta.md

Add Flutter and Dart release notes post

---

src/docs/development/ui/animations/implicit-animations.md

[翻译完成] implicit-animations.md
Resolves #584

[翻译完成] src/docs/development/ui/animations/implicit-animations.md

---

src/docs/development/packages-and-plugins/favorites.md

[翻译完成] favorites.md
Resolves #579

[翻译完成] src/docs/development/packages-and-plugins/favorites.md

---

src/docs/release/breaking-changes/nullable-cupertinothemedata-brightness.md

[翻译完成] nullable-cupertinothemedata-brightness.md
Resloves #600

[翻译完成] src/docs/release/breaking-changes/nullable-cupertinothemedata-brightness.md

---

src/docs/perf/deferred-components.md

Fixes a typo

---

src/docs/development/data-and-backend/google-apis.md

[翻译完成] src/docs/development/data-and-backend/google-apis.md
fix #870

[翻译完成] src/docs/development/data-and-backend/google-apis.md

---

src/desktop.md

[内容更新] src/desktop.md

---

src/_assets/js/archive.js

Fixes: #901 by updating to the new flutter_infra bucket.

Update the flutter_infra bucket.

---

src/docs/deployment/macos.md

[完成翻译] src/docs/deployment/macos.md

---

examples/README.md
src/docs/development/accessibility-and-localization/internationalization.md
src/docs/development/ui/animations/tutorial.md
src/docs/development/ui/interactive.md
src/docs/development/ui/layout/index.md
src/docs/development/ui/layout/tutorial.md

替换所有 `null_safety_examples` 为 `examples`

---

src/assets/js/subscribe.js
src/assets/js/subscribe_prefs.js
src/subscribe/index.html
src/subscribe/preferences.html
src/subscribe/subscribed.html

Update / Localized the Flutter subscribe page.

---

src/docs/release/breaking-changes/index.md
src/jobs/framework.html
src/jobs/index.md

[sync] 2021/7/28

---

src/community/tutorials/singleton-pattern-in-flutter-n-dart

Add Tutorial: Flutter(able) 的单例模式 by Jiakang

---

src/docs/null-safety.md

[完成翻译] src/docs/null-safety.md

---

src/docs/development/ui/interactive.md

[内容更新] src/docs/development/ui/interactive.md

---

src/docs/development/ui/layout/adaptive-responsive.md

[完成翻译] src/docs/development/ui/layout/adaptive-responsive.md

---

src/docs/development/ui/layout/building-adaptive-apps.md

https://github.com/cfug/flutter.cn/pull/904#pullrequestreview-735491935

[内容更新] src/docs/development/ui/layout/building-adaptive-apps.md

---

src/docs/development/accessibility-and-localization/internationalization.md

Improve country code explanation

---

src/docs/get-started/codelab.md

fixed mistake of 'row' at 'before each row in the ListView'.

[sync] 2021/9/1

---

src/docs/development/ui/layout/index.md

[内容修订] src/docs/development/ui/layout/index.md

---

src/docs/get-started/web.md

- 修复标题 IDE 的标题等级
- 部分未翻译的内容进行了翻译

[内容修订] src/docs/get-started/web.md

---

src/docs/development/packages-and-plugins/using-packages.md

fix #970 
`maximim` -> `maximum`

[内容修订] src/docs/development/packages-and-plugins/using-packages.md

---

src/docs/development/tools/vs-code.md

Fix #973 .
移除重复语句并修正列表格式，英文内容与原文档同步。

[内容修订] src/docs/development/tools/vs-code.md

---

src/docs/development/tools/hot-reload.md

[内容修订] src/docs/development/tools/hot-reload.md

---

src/docs/cookbook/testing/widget/introduction.md
src/docs/deployment/ios.md
src/docs/development/packages-and-plugins/developing-packages.md
src/docs/development/tools/vs-code.md
src/docs/development/ui/animations/implicit-animations.md
src/docs/development/ui/layout/adaptive-responsive.md
src/docs/resources/faq.md

[内容修订] 修正部分 `:` <=> `<br>` 问题

---

src/docs/cookbook/testing/widget/finders.md

[内容修订] src/docs/cookbook/testing/widget/finders.md

---

src/desktop.md
src/docs/development/data-and-backend/json.md
src/docs/development/platform-integration/web.md
src/docs/development/tools/vs-code.md
src/docs/development/ui/animations/hero-animations.md
src/docs/get-started/flutter-for/react-native-devs.md
src/docs/resources/faq.md
src/docs/testing/code-debugging.md
src/docs/testing/debugging.md

Fix #965 .
根据 #965 排查出的链接问题，处理了部分无效的链接，同时更新了一些并未对齐的原文/译文内容。

[内容修订] 修复部分错误的链接

---

src/dash/index.md

[完成翻译] src/dash/index.md

---

src/docs/development/data-and-backend/firebase.md
src/docs/development/packages-and-plugins/developing-packages.md
src/docs/development/platform-integration/web.md
src/docs/resources/faq.md

Fixes #981 .
参考 #983 的检查，进一步修复了无效的链接引用。

[内容修订] 修复无效的链接引用 pt.2

---

src/docs/development/tools/flutter-fix.md

[完成翻译] src/docs/development/tools/flutter-fix.md

---

.github/workflows/check.yml
tool/html_check_reference_links.py

使用了与部署网站时相同的构建工具，应该有效降低了漏报/误报。
- https://github.com/cfug/flutter.cn/runs/3793095767?check_suite_focus=true
- #988
- cfug/dart.cn#335

[Infrastructure] Update link references check

---

src/docs/release/breaking-changes/theme-data-accent-properties.md

[完成翻译] src/docs/release/breaking-changes/theme-data-accent-properties.md

---

src/about/docs-cn.md
src/community/china.md

Add Qiniu to contributor list

---

src/development/tools/sdk/release-notes/supported-platforms.md

[完成翻译] src/development/tools/sdk/release-notes/supported-platforms.md

---

src/perf/rendering/shader.md

[完成翻译] src/perf/rendering/shader.md

---

src/perf/deferred-components.md

**请点击「Preview」选择提交 PR 的模板**：
- [新增翻译](?template=2_localization_submission.md)

[内容修订] src/docs/perf/deferred-components.md

---

src/get-started/install/_path-linux-chromeos.md

Fixes: #1019
根据 @1191000606 的反馈作出了一些修改。

[内容修订] src/get-started/install/_path-linux-chromeos.md

---

src/get-started/install/_ios-setup.md

[内容修订] src/get-started/install/_ios-setup.md

---

src/development/tools/devtools/memory.md
src/development/tools/hot-reload.md

[内容修订] 部分内容修复

---

src/deployment/windows.md

[完成翻译] src/deployment/windows.md

---

src/development/platform-integration/platform-channels.md

[内容修订] src/development/platform-integration/platform-channels.md

---

src/_data/sidenav.yml
src/development/tools/pubspec.md

[完成翻译] src/development/tools/pubspec.md

---

src/deployment/web.md

文章中一处widget漏了字母t
Fix #1058 .
修正单词拼写错误

[内容修订] src/deployment/web.md

---

src/development/tools/sdk/releases.md

Credits to @tyisme614 , thanks!

Add Flutter Merge bot intro.

---

src/desktop/index.md

1. 根据原文格式化`snapd`；
2. 修正`myapp`为`my_app`。
**请点击「Preview」选择提交 PR 的模板**：

修正排版以及配置拼写

---

src/_includes/docs/catalogpage.html
src/development/ui/widgets/index.md

Fix #1095.
替换 `site.url` 为 `site.main-url` 以去除冗余的 `/docs`。

[内容修订] src/development/ui/widgets/index.md

---

tool/translator/build.sh
tool/translator/package.json

ref: https://github.com/cfug/team/issues/30

fix: 生成单中文翻译结果，以试验 SEO 效果

---

src/development/add-to-app/android/add-flutter-screen.md

[内容修订] src/development/add-to-app/android/add-flutter-screen.md

---

src/development/add-to-app/android/add-flutter-fragment.md

[内容修订] src/development/add-to-app/android/add-flutter-fragment.md

---

src/resources/platform-adaptations.md

Fix #1117.
替换 `成为` 为 `称为` ，修复笔误。

[内容修订] src/resources/platform-adaptations.md

---

src/development/ui/animations/overview.md

Fix #1120 
删除[src/development/ui/animations/overview.md](https://github.com/cfug/flutter.cn/blob/master/src/development/ui/animations/overview.md)中关于Tickers的描述一节，重复的文本：
`一个 Ticker 可以被启动和停止，启动时，它会返回一个 Future，这个 Future 在 Ticker 停止时会被改为完成状态。`

[内容修订] src/development/ui/animations/overview.md

---

src/perf/shader.md

Related Issue #1119
这里的中英文重复出现应该是因为翻译工具把这里 1. 2. 3. 识别为 markdown 列表了，所以需要用列表的方式写中文。

Update the translation format.

---

src/perf/index.md
src/posts/announcing-flutter-1-20.md
src/posts/whats-new-in-flutter-2-2.md
src/reference/tutorials.md

[内容修订] Fix page issues

---

src/development/ui/animations/hero-animations.md

Fix #1122
如下图所示，文档[src/development/ui/animations/hero-animations.md](https://github.com/cfug/flutter.cn/tree/master/src/development/ui/animations/hero-animations.md)对应的视频有误。
修改“主动画 (Hero animations)#标准Hero动画”这里的视频为：
[[Flutter 中文文档内嵌使用] - Radial Hero Animation - Stagger Demo- Standard Hero Animati](https://www.bilibili.com/video/BV1j441157TP?p=3&vd_source=c409f80ad8f29f54253f386178cdd5c4)

[内容修订] src/development/ui/animations/hero-animations.md

---

src/development/tools/sdk/release-notes/supported-platforms.md

**请点击「Preview」选择提交 PR 的模板**：
- [新增翻译](?template=2_localization_submission.md)

[内容修订] src/development/tools/sdk/release-notes/supported-platforms.md

---

src/development/packages-and-plugins/using-packages.md

- Fix #1130.
- 删除这个文件 `src/development/packages-and-plugins/using-packages.md` 中的重复内容。

[内容修订]  src/development/packages-and-plugins/using-packages.md

---

src/posts/whats-new-in-flutter-3-3.md

[内容修订] src/posts/whats-new-in-flutter-3-3.md

---

src/community/china.md

ref: https://github.com/cfug/flutter.cn/issues/1135

Update Tencent Cloud Mirror Known issues #1135

---

src/development/packages-and-plugins/developing-packages.md

[内容修订] {src/development/packages-and-plugins/developing-packages.md}

---

src/codelabs/index.md
src/development/data-and-backend/firebase.md
src/development/data-and-backend/state-mgmt/options.md
src/development/tools/devtools/inspector.md
src/development/ui/advanced/slivers.md
src/development/ui/layout/building-adaptive-apps.md
src/perf/best-practices.md
src/perf/index.md
src/perf/ui-performance.md
src/resources/architectural-overview.md
src/resources/games-toolkit.md
src/resources/videos.md
src/whats-new.md

整理了发布在哔哩哔哩渠道的 67 个视频与 YouTube 视频的对应关系，初步替换这些已经上载的视频链接。

Replace YT videos to Bilibili

---

src/posts/index.md
src/posts/partnering-with-github-on-an-supply-chain-security.md

Add Post: GitHub 供应链安全已支持 Dart 开发者生态

---

.devcontainer/devcontainer.json
.github/workflows/build.yml
Dockerfile
tool/check-links.sh
tool/translator/build.sh

这个 PR 用于此次文档同步中 CI 的问题解决。
不知道为什么 `.devcontainer/devcontainer.json` 这个文件会导致 codespace 启动失败，所以先 bye bye 了您嘞。

Fixes CI process.

---

.github/workflows/build.yml
src/cookbook/gestures/dismissible.md
src/cookbook/gestures/handling-taps.md
src/cookbook/lists/floating-app-bar.md
src/cookbook/navigation/named-routes.md
src/cookbook/navigation/navigation-basics.md
src/cookbook/navigation/passing-data.md
src/cookbook/navigation/returning-data.md
src/cookbook/persistence/sqlite.md
src/get-started/flutter-for/react-native-devs.md

之前的 CI 修复留下了 Code Test 的问题，现在调整为不允许失败，看看哪里出现了问题。

[CI Fixes] Turn on the test on Stable channel

---

src/perf/deferred-components.md

[内容修订] src/perf/deferred-components.md

---

src/development/ui/assets-and-images.md

[内容修订] src/development/ui/assets-and-images.md

---

src/posts/announcing-flutter-3-7.md
src/posts/index.md

Add Localized post about Flutter 3.7.

Add Flutter 3.7 Post

---

.github/workflows/build.yml
.github/workflows/link-check.yml
firebase.json
src/_includes/header.html
tool/check-links.sh

Perform the docs moving step first during the deployment.

Move docs before build and deploy

---

src/development/platform-integration/macos/building.md

[翻译完成] flutter.cn/src/development/platform-integration/macos/building.md
Resolves https://github.com/cfug/flutter.cn/issues/1194

[翻译完成] flutter.cn/src/development/platform-integration/macos/building.md

---

src/get-started/codelab.md

fix next page nav in page footer
**请点击「Preview」选择提交 PR 的模板**：
- [新增翻译](?template=2_localization_submission.md)

fix next page nav in page footer 编写第一个 Flutter 应用

---

src/deployment/ios.md

[内容修订] src/deployment/ios.md

---

_config.yml
src/_includes/breadcrumbs.html

https://jekyllrb.com/docs/configuration/front-matter-defaults/

update Jekyll config for breadcrumb

---

src/development/ui/widgets-intro.md

[内容修订] src/development/ui/widgets-intro.md

---

src/development/ui/layout/building-adaptive-apps.md

[内容修订] src/development/ui/layout/building-adaptive-apps.md

---

src/cookbook/navigation/named-routes.md
src/cookbook/navigation/navigate-with-arguments.md
src/deployment/android.md
src/development/add-to-app/ios/add-flutter-screen.md
src/development/platform-integration/android/c-interop.md
src/development/tools/devtools/overview.md
src/get-started/flutter-for/web-devs.md
src/perf/app-size.md
src/resources/books.md
src/resources/bootstrap-into-dart.md
src/resources/faq.md
src/testing/debugging.md

- #1144 
- #1145 
- #1147 
- #1148
- #1149
- #1151
- #1152
- #1154
- #1155
- #1156
- #1157
- #1149 
- 修改文本位置（issue 中认为重复的地方，实际上是翻译文本放错了位置 ）
- 补全其他未翻译的文本
- #1156 
- 修改 JavaScript 拼写错误 web-devs.md
- 翻译文本 bootstrap-into-dart.md
- #1155 
- 修改 issue 和 PR 的链接
- 翻译文本
- 其他 issues 按照内容修改

[内容修订] 微小改动部分文档

---

src/testing/integration-tests/index.md

Resolve #1206、#1281 
#1153 之前已经被修复，可以关闭了。

[完成翻译] src/testing/integration-tests/index.md

---

src/development/ui/animations/hero-animations.md
src/perf/best-practices.md

Resolve #1061  #1208 
Fix #1283 
- #1061 
- 补全最新的文档内容 https://docs.flutter.dev/perf/best-practices 
- 翻译文档
- #1283 
- 替换正确的视频地址

[完成翻译] src/perf/best-practices.md

---

src/tools/devtools/performance.md

Resolve #1223 
* 修复锚点链接错误、小标题错误
* 翻译文本

[完成翻译] src/tools/devtools/performance.md

---

src/add-to-app/ios/project-setup.md

Resolve #1222 
1. 修复文本格式错位问题
2. 翻译文本

[完成翻译] src/add-to-app/ios/project-setup.md

---

src/platform-integration/windows/run-loop-migration.md

[完成翻译] src/platform-integration/windows/run-loop-migration.md

---

src/packages-and-plugins/developing-packages.md

Resolve #1221 
1. 文档中写的是 `CmakeFile.txt`，但根据以下指令生成的模板，`src` 目录内实际是 `CMakeLists.txt`。
```terminal
$ flutter create --template=plugin_ffi hello
```
2. 翻译文本

[完成翻译] src/packages-and-plugins/developing-packages.md

---

src/resources/inside-flutter.md

[完成翻译] src/resources/inside-flutter.md

---

src/ui/navigation/url-strategies.md

[完成翻译] src/ui/navigation/url-strategies.md

---

src/ui/animations/index.md

[完成翻译] src/ui/animations/index.md

---

src/reference/flutter-cli.md

[完成翻译] src/reference/flutter-cli.md

---

src/resources/inside-flutter.md

Fix #1306 
更正 inside-flutter 中关于 element 树部分的翻译。

[内容修订] src/resources/inside-flutter.md

---

src/release/breaking-changes/index.md

Resolve #1164 
1. 修复文本位置错误
2. 翻译文本

[完成翻译] src/release/breaking-changes/index.md

---

src/release/breaking-changes/flutter-driver-migration.md

Resolve #1207 
1. 与上游 PR 内容同步
https://github.com/flutter/website/pull/8860
2. 翻译文本

[完成翻译] src/release/breaking-changes/flutter-driver-migration.md

---

src/resources/bug-reports.md

[完成翻译] src/resources/bug-reports.md

---

src/development/tools/sdk/release-notes/index.md

[完成翻译] src/development/tools/sdk/release-notes/index.md

---

src/platform-integration/ios/ios-debugging.md

[完成翻译] src/platform-integration/ios/ios-debugging.md

---

src/tools/devtools/network.md

Resolve #1203 
1. 与上游 PR 内容同步
https://github.com/flutter/website/pull/8850
2. 翻译文本

[完成翻译] src/tools/devtools/network.md

---

src/platform-integration/desktop.md

[内容修订] src/platform-integration/desktop.md

---

src/accessibility-and-localization/accessibility.md
src/community/tutorials/flutter-state-management-with-mobx.md
src/data-and-backend/state-mgmt/options.md
src/get-started/flutter-for/ios-devs.md
src/index.md
src/packages-and-plugins/using-packages.md
src/perf/index.md
src/platform-integration/web/index.md
src/posts/Flutter-io19.md
src/posts/announcing-dart-2-12.md
src/posts/announcing-flutter-1-12.md
src/posts/announcing-flutter-1-7-9.md
src/posts/dev-story-beike-use-flutter-service-300-million-users.md
src/posts/flutter-bytedance-dev-story.md
src/posts/flutter-engage-china-developers-qa-part-2.md
src/posts/flutter-engage-china-event-recap.md
src/posts/flutter-engage-event-recap.md
src/posts/flutter-news-from-gdd-china-flutter1.9.md
src/posts/flutter-pubg-mobile-dev-story.md
src/posts/google-i-o-2021-flutter-workshops.md
src/posts/google-io-2021-flutter-recap.md
src/reference/widgets.md
src/release/whats-new.md
src/resources/videos.md
src/ui/animations/hero-animations.md
src/ui/animations/implicit-animations.md
src/ui/animations/staggered-animations.md
src/ui/layout/building-adaptive-apps.md
src/ui/layout/index.md

Fix #1323 
1. Bilibili 内嵌视频禁用自动播放
2. 修复 `/src/resources/videos.md` 视频错误
https://github.com/cfug/flutter.cn/blob/62a90e9f45c95f3235809a4806cce3d3b9eef407/src/resources/videos.md?plain=1#L105-L108

[内容修订] 文档内嵌视频禁用自动播放

---

src/resources/faq.md

Fix #1325 
与 https://github.com/cfug/flutter.cn/pull/1310 翻译同步

[内容修订] src/resources/faq.md

---

src/ui/advanced/slivers.md

[完成翻译] src/ui/advanced/slivers.md

---

src/platform-integration/ios/platform-views.md

[内容修订] src/platform-integration/ios/platform-views.md

---

src/perf/best-practices.md

Fix #1331 
已经翻译过了
Resolve #1208

[内容修订] src/perf/best-practices.md

---

src/resources/videos.md

[内容修订] src/resources/videos.md

---

src/release/breaking-changes/androidx-migration.md

[完成翻译] src/release/breaking-changes/androidx-migration.md

---

src/platform-integration/windows/version-migration.md

[完成翻译] src/platform-integration/windows/version-migration.md

---

src/perf/index.md

[内容修订] src/perf/index.md

---

src/_includes/docs/cookbook-toc.md

Fix #1295 
```diff
- site.url
+ site.main-url
```

Fix cookbook-toc URL

---

src/_includes/docs/china-notice.md

Fix: #1347 
这句话被以引用的方式更新在 includes/docs 中，需要做翻译以及更新链接。

[内容修订] 更新中国镜像翻译和描述

---

src/cookbook/testing/widget/scrolling.md

[完成翻译] src/cookbook/testing/widget/scrolling.md

---

src/get-started/codelab.md

[内容修订] src/get-started/codelab.md

---

src/add-to-app/android/project-setup.md

Fix #1354
主要内容已经在 #1348 中修复。
当前 PR 更新了一下与这个相同的问题。

[内容修订] src/add-to-app/android/project-setup.md

---

src/_data/sidenav.yml
src/ui/accessibility-and-internationalization/accessibility.md
src/ui/accessibility-and-internationalization/index.md

Resolve #1356 
- 翻译补全 accessibility 中的内容
- 修改不正确的格式
- 修改菜单名称，与相邻菜单的形式相同
Issue #1356 的主要问题已经在 PR #1357 中解决。

[完成翻译] src/ui/accessibility-and-internationalization/accessibility.md

---

src/_includes/inline-toc.html
src/_includes/side-toc.html

[完成翻译] toc 中的目录

---

src/ui/accessibility-and-internationalization/internationalization.md

[完成翻译] src/ui/accessibility-and-internationalization/internationalization.md

---

src/data-and-backend/networking.md

[完成翻译] src/data-and-backend/networking.md

---

src/ui/accessibility-and-internationalization/internationalization.md

- 同步上游
https://github.com/flutter/website/pull/9785

[内容修订] src/ui/accessibility-and-internationalization/internationalization.md

---

.firebaserc
.github/workflows/stage.yml
src/deployment/android.md

* feat: add preview URL to the i18n PR
* test for .md file update

Test for adding Firebase Hosting Preview link in PRs (Part: 1)

---

src/index.md

[内容修订] src/index.md

---

src/_includes/docs/dart-tool-win.md
src/get-started/install/windows.md

无关联 issues
- 增补翻译
- 修订格式不正确的问题

[完成翻译] src/get-started/install/windows.md

---

src/get-started/install/_android-setup-chromeos.md
src/get-started/install/_chrome-setup-chromeos.md
src/get-started/install/chromeos.md

[完成翻译] src/get-started/install/chromeos.md

---

src/get-started/install/_ios-setup.md
src/get-started/install/macos.md

无关联 issues
- 增补翻译
- 删除重复翻译
- 同步上游 https://github.com/flutter/website/pull/9799

[完成翻译] src/get-started/install/macos.md

---

.github/workflows/stage.yml
src/posts/Flutter-io19.md

Testing Firebase Hosting running with branch.

---

.github/workflows/stage.yml
Dockerfile
Makefile
_config_stage.yml
tool/translator/build.sh

In order to override `{{site.url}}` for builds.

👷 Support explicitly `stage` builds

---

src/get-started/editor.md

[完成翻译] src/get-started/editor.md

---

src/ui/layout/responsive/building-adaptive-apps.md

- [内容修订](?template=building-adaptive-apps.md)

[内容修订]/src/ui/layout/responsive/building-adaptive-apps

---

src/_data/sidenav.yml
src/cookbook/maintenance/error-reporting.md
src/posts/how-its-made-i-o-photo-booth.md
src/posts/whats-new-in-flutter-2-2.md

其他类似链接已向上游提交，将在下次同步得到更新：
- https://github.com/flutter/website/pull/9894

Update firebase.google.com -> firebase.google.cn

---

.github/workflows/stage.yml

Skip Firebase staging for repo forks

---

_config.yml
src/_layouts/base.html

Test using GTM to add GA code.

Add GA code

---

src/ui/animations/staggered-animations.md

[内容修订] src/ui/animations/staggered-animations.md

---

src/resources/videos.md

[内容修订] src/resources/videos

---

src/posts/announcing-dart-3-2.md
src/posts/whats-new-in-flutter-3-16.md

add announcing-dart-3-2.md and whats-new-in-flutter-3-16.md post file

add new posts

---

.github/workflows/build.yml

提交至 main 分支时，无法触发链接检查，
https://github.com/cfug/flutter.cn/blob/ec513e5b24840bded651cad17c29e1dc93d6780f/.github/workflows/build.yml#L45-L48
进而影响部署。
https://github.com/cfug/flutter.cn/blob/ec513e5b24840bded651cad17c29e1dc93d6780f/.github/workflows/build.yml#L66-L73
所有情况都应该需要链接检查。

Fix: link check not triggered on deploy

---

src/_includes/docs/install/compiler/android.md
src/_includes/docs/install/devices/android-emulator.md
src/_includes/docs/install/devices/android-physical.md
src/_includes/docs/install/flutter-doctor.md
src/_includes/docs/install/flutter-sdk.md
src/_includes/docs/install/flutter/vscode.md
src/_includes/docs/install/next-steps.md
src/_includes/docs/install/reqs/flutter-sdk/flutter-doctor-precedence.md
src/_includes/docs/install/reqs/windows/base.md
src/_includes/docs/install/reqs/windows/software.md
src/get-started/install/windows/mobile.md

[完成翻译] src/get-started/install/windows/mobile.md

---

src/data-and-backend/serialization/json.md

[内容修订] {src/data-and-backend/serialization/json.md}

---

src/_includes/docs/install/reqs/windows/base.md

| ❌ | ✅ |
| --- | --- |
| ![1](https://github.com/cfug/flutter.cn/assets/32262985/effe3f4b-9be6-4b14-881a-bf8bfd296681) | ![2](https://github.com/cfug/flutter.cn/assets/32262985/586e7fb2-4d4d-4814-ba65-0b885712dbe0) |

Fix: Table Format (get-started/install/)

---

src/get-started/install/windows/web.md

[完成翻译] src/get-started/install/windows/web.md

---

src/get-started/install/windows/desktop.md

[完成翻译] src/get-started/install/windows/desktop.md

---

tool/translator/gulpfile.js

| Before<sup>(flutter.cn)</sup>  | After<sup>(flutter.cn)</sup> | flutter.dev |  
| --- | --- | --- |  
| ![1](https://github.com/cfug/flutter.cn/assets/32262985/099bffbd-1cb6-4d64-a223-3a4703b8c81c) | ![2](https://github.com/cfug/flutter.cn/assets/32262985/d3dba236-41b3-41a1-8d01-f09f0efbea8f) | ![3](https://github.com/cfug/flutter.cn/assets/32262985/15685eef-fa6b-4c9f-aeb0-7835b115f6ec) |

Update: TOC Style

---

src/_layouts/base.html

fixes: update the static-file cdn domain.

---

src/_includes/head-diff2html.html
src/_layouts/base.html

Update: cdn.staticfile.org -> cdn.staticfile.net

---

src/perf/ui-performance.md

[内容修订] src/perf/ui-performance.md

---

src/posts/index.md

- 补充 2024 年的博客列表。
- 调整所有博文按照发布时间排序，从新到旧。

[内容修订] src/posts/index.md

---

src/tos/index.md

[内容修订] src/tos/index.md

---

src/platform-integration/web/renderers.md

[内容修订] src/platform-integration/web/renderers.md

---

src/index.md

Reverts cfug/flutter.cn#1432
> PR https://github.com/flutter/website/pull/10428

Revert: "[内容修订] src/index.md" PR1432

---

src/_includes/docs/install/compiler/xcode.md
src/_includes/docs/install/devices/ios-simulator.md

[内容修订] src/get-started/install/macos

---

src/_includes/docs/install/flutter/download.md
src/_includes/docs/install/flutter/vscode.md
src/_includes/docs/install/reqs/windows/set-path.md
src/content/get-started/codelab-web.md

Fix: header wrapper

---

.github/workflows/stage.yml

替换前
```
https://flutter-cn-docs-prod--pr1480-flutter-gpu-review-63fg5hif.web.appsrc/content/posts/dart-3-5.html
```
替换后
```
https://flutter-cn-docs-prod--pr1480-flutter-gpu-review-63fg5hif.web.app/posts/dart-3-5.html
```

Update Firebase PR comment config.

---

src/content/cookbook/effects/shimmer-loading.md

[完成翻译] src/content/cookbook/effects/shimmer-loading.md

---

src/content/get-started/codelab.md

[完成翻译] src/content/get-started/codelab.md

---

.github/workflows/build.yml
.github/workflows/stage.yml
src/_data/site.yml
src/_layouts/base.html
tool/flutter_site/lib/src/commands/build.dart

修复网站未使用 `--release` 构建生产环境导致的一系列问题。
（如：isProduction == false，网站修改时间不准确等等）

Fix: Build site for production

---

src/content/get-started/fundamentals/dart.md

[完成翻译] src/content/get-started/fundamentals/dart.md

---

src/content/community/china/index.md

[内容修订] src/content/community/china/index.md

---

src/content/get-started/fundamentals/widgets.md

[完成翻译] src/content/get-started/fundamentals/widgets.md
Resolve #1508

[完成翻译] src/content/get-started/fundamentals/widgets.md

---

.github/workflows/translator_bot.yml

Translator Bot 说明：https://github.com/cfug/translator_bot

CI: Translator Bot
