- src/docs/development/data-and-backend/state-mgmt/simple.md
https://github.com/filiph/samples/tree/provider-shopper/provider_shopper  is 404
I get the new URL from  https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple
> can't open example url with 404. update it

- src/posts/Flutter-io19.md
- src/posts/announcing-adobe-xd-support-for-flutter.md
- src/posts/announcing-flutter-1-12.md
- src/posts/announcing-flutter-1-20.md
- src/posts/announcing-flutter-1-7-9.md
- src/posts/flutter-development-on-a-pixelbook.md
- src/posts/flutter-news-from-gdd-china-flutter1.9.md
- src/posts/launching-flutter-12-at-mobile-world.md
双语文档显示工具忽略了 post/ 目录，因此需要将本目录下面的文章中的英文删除。
未来再同步进来的官方博客内容，也无需再加入英文。
> Delete the english under the post/ articles

- .gitmodules
Redirect site-shared from https://github.com/dart-lang/site-shared to https://github.com/cfug/site-shared.
Wikis need further updates.
> Redirect site shared

- src/_layouts/base.html
#1064 
`meta` 标签缺少一个引号。
原文
`<meta name="twitter:site" content="@flutterchina>`
> [内容修订] src/_layouts/base.html

- CODEOWNERS
Using the @cfug/localization group as the CODEOWNERS instead of specified users.
> [Infra] 🔒️ Request @cfug/localization as CODEOWNERS

- src/_includes/docs/cookbook-group-index.md
Fix: #1102 
这个文件复制动态的生成 cookbook 的 URL，替换 `site.url` 为 `site.main-url` 即可。
> Fix the Cookbook URLs.

- src/development/ios-project-migration.md
> [完成翻译] src/development/ios-project-migration.md

- firebase.json
- src/_includes/header.html
I think the problem wasn't the redirect itself, as the other redirects don't include `/docs`, but rather the header had an outdated link without a redirect. 
Tracking a similar fix up-stream in https://github.com/flutter/website/pull/8289#discussion_r1113841877
> Revert change to redirect by fixing header

- src/get-started/index.md
> [内容修订] src/get-started/index.md

- src/release/breaking-changes/splash-screen-migration.md
> [完成翻译] src/release/breaking-changes/splash-screen-migration.md

- src/_includes/page-github-links.html
> Fix report icon not displayed

- src/_includes/docs/install/flutter-sdk.md
- src/_includes/docs/install/flutter/download.md
- src/_includes/docs/install/flutter/vscode.md
- src/_includes/docs/install/reqs/windows/open-envvars.md
- src/_includes/docs/install/reqs/windows/set-path.md
无关联 issues
安装 Flutter SDK - 自行下载安装的翻译增补。
> [完成翻译] src/get-started/install/windows/mobile

- _config.yml
> Update: codelabs for site variable

- _config.yml
- src/codelabs/index.md
替换能够在 https://codelabs.flutter-io.cn 上访问的 codelabs。
> Update: Chinese mirror of codelabs

- src/content/resources/architectural-overview.md
无
关于 CanvasKit 词条的超链接错误
参考 Flutter [国际站点](https://docs.flutter.dev/resources/architectural-overview) 内对于该词条的超链接应为 https://skia.org/docs/user/modules/canvaskit/
> [内容修订] src/content/resources/architectural-overview.md

- src/content/posts/whats-new-in-flutter-3-24.md
- tool/translator/gulpfile.js
> Fix: translator - gulpfile.js

- src/content/cookbook/effects/download-button.md
> [完成翻译] src/content/cookbook/effects/download-button.md

- src/content/cookbook/effects/download-button.md
- src/content/cookbook/effects/nested-nav.md
> [完成翻译] src/content/cookbook/effects/nested-nav.md

- src/content/cookbook/effects/drag-a-widget.md
> [完成翻译] src/content/cookbook/effects/drag-a-widget.md

- src/content/platform-integration/web/renderers.md
> [完成翻译] src/content/platform-integration/web/renderers.md

- .github/workflows/build.yml
- .github/workflows/stage.yml
- tool/translator/robots.txt
目前在 `actions/checkout` (GitHub Action) 中未取出所有历史记录，
导致所有页面底部的更新时间都会被统一到最近 1 次的提交时间。
预期：所有页面对应各自的最新更新时间。
影响范围：所有页面和 [sitemap.xml](https://docs.flutter.cn/sitemap.xml)
> 11ty 关于内容日期的文档 (git Last Modified)： https://www.11ty.dev/docs/dates/
> Fix: Page last updated

- src/content/get-started/flutter-for/android-devs.md
Fix image suffix mismatch in description
- [内容修订](?template=src/content/get-started/flutter-for/android-devs.md)
> [内容修订] src/content/get-started/flutter-for/android-devs.md

- src/content/get-started/flutter-for/dart-swift-concurrency.md
Small PR - fixes the broken Async Weather example reference. Relevant page: https://docs.flutter.cn/get-started/flutter-for/dart-swift-concurrency
> Fix Async Weather example
